
# This is an auto-generated file. Do not edit this file manually.
variable "target_ai_core_model" {
  type        = list(any)
  description = "Defines the target AI core model to be used by the AI Core service"
  default     = ["gpt-35-turbo"]

  validation {
    condition = length([
      for o in var.target_ai_core_model : true
      if contains([        
        "amazon--nova-lite",
        "amazon--nova-micro",
        "amazon--nova-pro",
        "amazon--titan-embed-text",
        "amazon--titan-text-express",
        "amazon--titan-text-lite",
        "anthropic--claude-3-haiku",
        "anthropic--claude-3-opus",
        "anthropic--claude-3-sonnet",
        "anthropic--claude-3.5-sonnet",
        "chat-bison",
        "gemini-1.0-pro",
        "gemini-1.5-flash",
        "gemini-1.5-pro",
        "gpt-35-turbo",
        "gpt-35-turbo-0125",
        "gpt-35-turbo-16k",
        "gpt-4",
        "gpt-4-32k",
        "gpt-4o",
        "gpt-4o-mini",
        "ibm--granite-13b-chat",
        "meta--llama3.1-70b-instruct",
        "mistralai--mistral-large-instruct",
        "o1",
        "o3-mini",
        "text-bison",
        "text-embedding-3-large",
        "text-embedding-3-small",
        "text-embedding-ada-002",
        "textembedding-gecko",
        "textembedding-gecko-multilingual",
      ], o)
    ]) == length(var.target_ai_core_model)
    error_message = "Please enter a valid entry for the target_ai_core_model of the AI Core service. See https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/models-and-scenarios-in-generative-ai-hub (Model Name) for the list of supported values."  
  }
}

