
# This is an auto-generated file. Do not edit this file manually.
variable "target_ai_core_model" {
  type        = list(any)
  description = "Defines the target AI core model to be used by the AI Core service"
  default     = ["gpt-35-turbo"]

  validation {
    condition = length([
      for o in var.target_ai_core_model : true
      if contains([
        "amazon--nova-lite",
        "amazon--nova-micro",
        "amazon--nova-premier",
        "amazon--nova-pro",
        "amazon--titan-embed-image",
        "amazon--titan-embed-text",
        "amazon--titan-text-express",
        "amazon--titan-text-lite",
        "anthropic--claude-3-haiku",
        "anthropic--claude-3-opus",
        "anthropic--claude-3.5-sonnet",
        "anthropic--claude-3.7-sonnet",
        "anthropic--claude-4-opus",
        "anthropic--claude-4-sonnet",
        "cohere--command-a-reasoning",
        "cohere-reranker",
        "gemini-2.0-flash",
        "gemini-2.0-flash-lite",
        "gemini-2.5-flash",
        "gemini-2.5-pro",
        "gemini-embedding",
        "gpt-35-turbo",
        "gpt-35-turbo-0125",
        "gpt-4",
        "gpt-4.1",
        "gpt-4.1-mini",
        "gpt-4.1-nano",
        "gpt-4o",
        "gpt-4o-mini",
        "gpt-5",
        "gpt-5-mini",
        "gpt-5-nano",
        "ibm--granite-13b-chat",
        "meta--llama3.1-70b-instruct",
        "mistralai--mistral-large-instruct",
        "mistralai--mistral-medium-instruct",
        "mistralai--mistral-small-instruct",
        "nvidia--llama-3.2-nv-embedqa-1b",
        "o1",
        "o3",
        "o3-mini",
        "o4-mini",
        "sonar",
        "sonar-pro",
        "text-embedding-3-large",
        "text-embedding-3-small",
        "text-embedding-ada-002",
      ], o)
    ]) == length(var.target_ai_core_model)
    error_message = "Please enter a valid entry for the target_ai_core_model of the AI Core service. See https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/models-and-scenarios-in-generative-ai-hub (Model Name) for the list of supported values."
  }
}

